### ISSUE TITLE
Language toggle

### ISSUE THREAD

**Issue by lzachmann** [csp-inc/fluvius-frontend#11]
Our partners will help us translate any / all project narrative, but we need a Portuguese / English toggle somewhere in the app. Here's an example. 

<img width="1124" alt="Screen Shot 2022-02-03 at 10 20 28 AM" src="https://user-images.githubusercontent.com/7574887/152394885-16e5a7df-509a-4c21-9617-2498acd8fc46.png">

**Comment by ericcsp** [comment]
Portuguese toggle added... if mapbox relabeling is necessary, please re-open
